//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APMDatabaseEntities : DbContext
    {
        public APMDatabaseEntities()
            : base("name=APMDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__Employee> C__Employee { get; set; }
        public virtual DbSet<C__EmployeeEmergeLeave> C__EmployeeEmergeLeave { get; set; }
        public virtual DbSet<C__EmployeeSalaryComponent> C__EmployeeSalaryComponent { get; set; }
        public virtual DbSet<C__Roster> C__Roster { get; set; }
        public virtual DbSet<C__SalaryComponent> C__SalaryComponent { get; set; }
        public virtual DbSet<C__SalaryEmployeePayment> C__SalaryEmployeePayment { get; set; }
        public virtual DbSet<C__UserPassword> C__UserPassword { get; set; }
        public virtual DbSet<C_AccountJournal> C_AccountJournal { get; set; }
        public virtual DbSet<C_AccountJournalCostCenter> C_AccountJournalCostCenter { get; set; }
        public virtual DbSet<C_AccountJournalDetail> C_AccountJournalDetail { get; set; }
        public virtual DbSet<C_AccountJournalOrganization> C_AccountJournalOrganization { get; set; }
        public virtual DbSet<C_AttachmentImage> C_AttachmentImage { get; set; }
        public virtual DbSet<C_AttendanceCode> C_AttendanceCode { get; set; }
        public virtual DbSet<C_AttendanceType> C_AttendanceType { get; set; }
        public virtual DbSet<C_BaseRate> C_BaseRate { get; set; }
        public virtual DbSet<C_BaseRateAttendanceCode> C_BaseRateAttendanceCode { get; set; }
        public virtual DbSet<C_BaseRateDetail> C_BaseRateDetail { get; set; }
        public virtual DbSet<C_BaseRateGroupType> C_BaseRateGroupType { get; set; }
        public virtual DbSet<C_BaseRateTag> C_BaseRateTag { get; set; }
        public virtual DbSet<C_BaseRateTag2> C_BaseRateTag2 { get; set; }
        public virtual DbSet<C_BlackListIdNumber> C_BlackListIdNumber { get; set; }
        public virtual DbSet<C_Branch> C_Branch { get; set; }
        public virtual DbSet<C_BranchAsset> C_BranchAsset { get; set; }
        public virtual DbSet<C_Break> C_Break { get; set; }
        public virtual DbSet<C_BreakDetail> C_BreakDetail { get; set; }
        public virtual DbSet<C_Calendar> C_Calendar { get; set; }
        public virtual DbSet<C_CalendarDetail> C_CalendarDetail { get; set; }
        public virtual DbSet<C_CashTransferField> C_CashTransferField { get; set; }
        public virtual DbSet<C_CashTransferFieldDetail> C_CashTransferFieldDetail { get; set; }
        public virtual DbSet<C_Claim> C_Claim { get; set; }
        public virtual DbSet<C_ClaimDetail> C_ClaimDetail { get; set; }
        public virtual DbSet<C_Class> C_Class { get; set; }
        public virtual DbSet<C_Competency> C_Competency { get; set; }
        public virtual DbSet<C_CompetencyAppraisal> C_CompetencyAppraisal { get; set; }
        public virtual DbSet<C_CompetencyBranch> C_CompetencyBranch { get; set; }
        public virtual DbSet<C_CompetencyCore> C_CompetencyCore { get; set; }
        public virtual DbSet<C_CompetencyCoreAppraisal> C_CompetencyCoreAppraisal { get; set; }
        public virtual DbSet<C_CompetencyCoreGrade> C_CompetencyCoreGrade { get; set; }
        public virtual DbSet<C_CompetencyCoreKeyAction> C_CompetencyCoreKeyAction { get; set; }
        public virtual DbSet<C_CompetencyCoreScale> C_CompetencyCoreScale { get; set; }
        public virtual DbSet<C_CompetencyFinalResult> C_CompetencyFinalResult { get; set; }
        public virtual DbSet<C_CompetencyGrade> C_CompetencyGrade { get; set; }
        public virtual DbSet<C_CompetencyJob> C_CompetencyJob { get; set; }
        public virtual DbSet<C_CompetencyJobResult> C_CompetencyJobResult { get; set; }
        public virtual DbSet<C_CompetencyKPI> C_CompetencyKPI { get; set; }
        public virtual DbSet<C_CompetencyKPIResult> C_CompetencyKPIResult { get; set; }
        public virtual DbSet<C_CostNotaDinas> C_CostNotaDinas { get; set; }
        public virtual DbSet<C_CostNotaDinasActivity> C_CostNotaDinasActivity { get; set; }
        public virtual DbSet<C_CostNotaDinasActivityDetail> C_CostNotaDinasActivityDetail { get; set; }
        public virtual DbSet<C_CostNotaDinasDetail> C_CostNotaDinasDetail { get; set; }
        public virtual DbSet<C_CostNotaDinasDetailJobTitle> C_CostNotaDinasDetailJobTitle { get; set; }
        public virtual DbSet<C_CostNotaDinasDetailTypeSchedule> C_CostNotaDinasDetailTypeSchedule { get; set; }
        public virtual DbSet<C_CostNotaDinasDetailTypeTransport> C_CostNotaDinasDetailTypeTransport { get; set; }
        public virtual DbSet<C_CostNotaDinasMatrix> C_CostNotaDinasMatrix { get; set; }
        public virtual DbSet<C_CostNotaDinasMatrixDetail> C_CostNotaDinasMatrixDetail { get; set; }
        public virtual DbSet<C_CurrencyRate> C_CurrencyRate { get; set; }
        public virtual DbSet<C_CustomField> C_CustomField { get; set; }
        public virtual DbSet<C_CustomFieldData> C_CustomFieldData { get; set; }
        public virtual DbSet<C_CustomFieldDefinition> C_CustomFieldDefinition { get; set; }
        public virtual DbSet<C_CustomFieldHistory> C_CustomFieldHistory { get; set; }
        public virtual DbSet<C_DropDownItem> C_DropDownItem { get; set; }
        public virtual DbSet<C_DropDownItemDetail> C_DropDownItemDetail { get; set; }
        public virtual DbSet<C_Employee> C_Employee { get; set; }
        public virtual DbSet<C_EmployeeBank> C_EmployeeBank { get; set; }
        public virtual DbSet<C_EmployeeBranchAsset> C_EmployeeBranchAsset { get; set; }
        public virtual DbSet<C_EmployeeCC> C_EmployeeCC { get; set; }
        public virtual DbSet<C_EmployeeCostCenter> C_EmployeeCostCenter { get; set; }
        public virtual DbSet<C_EmployeeDependent> C_EmployeeDependent { get; set; }
        public virtual DbSet<C_EmployeeDocument> C_EmployeeDocument { get; set; }
        public virtual DbSet<C_EmployeeEducation> C_EmployeeEducation { get; set; }
        public virtual DbSet<C_EmployeeEmergeClaim> C_EmployeeEmergeClaim { get; set; }
        public virtual DbSet<C_EmployeeEmergeLeave> C_EmployeeEmergeLeave { get; set; }
        public virtual DbSet<C_EmployeeEmergeRO> C_EmployeeEmergeRO { get; set; }
        public virtual DbSet<C_EmployeeExperience> C_EmployeeExperience { get; set; }
        public virtual DbSet<C_EmployeeExpertise> C_EmployeeExpertise { get; set; }
        public virtual DbSet<C_EmployeeLanguage> C_EmployeeLanguage { get; set; }
        public virtual DbSet<C_EmployeeOrganization> C_EmployeeOrganization { get; set; }
        public virtual DbSet<C_EmployeeReference> C_EmployeeReference { get; set; }
        public virtual DbSet<C_EmployeeRelative> C_EmployeeRelative { get; set; }
        public virtual DbSet<C_EmployeeTraining> C_EmployeeTraining { get; set; }
        public virtual DbSet<C_Grade> C_Grade { get; set; }
        public virtual DbSet<C_GroupData> C_GroupData { get; set; }
        public virtual DbSet<C_Holiday> C_Holiday { get; set; }
        public virtual DbSet<C_JamSosTek> C_JamSosTek { get; set; }
        public virtual DbSet<C_Job> C_Job { get; set; }
        public virtual DbSet<C_JobTitle> C_JobTitle { get; set; }
        public virtual DbSet<C_Leave> C_Leave { get; set; }
        public virtual DbSet<C_LeaveDetail> C_LeaveDetail { get; set; }
        public virtual DbSet<C_LNDTopic> C_LNDTopic { get; set; }
        public virtual DbSet<C_LNDTopicGroup> C_LNDTopicGroup { get; set; }
        public virtual DbSet<C_MinimumWageRegional> C_MinimumWageRegional { get; set; }
        public virtual DbSet<C_MinimumWageRegionalDetail> C_MinimumWageRegionalDetail { get; set; }
        public virtual DbSet<C_NomorReport1721A1> C_NomorReport1721A1 { get; set; }
        public virtual DbSet<C_NPPJamsostek> C_NPPJamsostek { get; set; }
        public virtual DbSet<C_Organization> C_Organization { get; set; }
        public virtual DbSet<C_OrganizationYear> C_OrganizationYear { get; set; }
        public virtual DbSet<C_OutputFile> C_OutputFile { get; set; }
        public virtual DbSet<C_OutputFileDetail> C_OutputFileDetail { get; set; }
        public virtual DbSet<C_OverTime> C_OverTime { get; set; }
        public virtual DbSet<C_OverTimeDetail> C_OverTimeDetail { get; set; }
        public virtual DbSet<C_OverTimeGroupOverTime> C_OverTimeGroupOverTime { get; set; }
        public virtual DbSet<C_OverTimeGroupTag> C_OverTimeGroupTag { get; set; }
        public virtual DbSet<C_PaymentSchedule> C_PaymentSchedule { get; set; }
        public virtual DbSet<C_PaySlipField> C_PaySlipField { get; set; }
        public virtual DbSet<C_PaySlipFieldDetail> C_PaySlipFieldDetail { get; set; }
        public virtual DbSet<C_PaySlipFieldDetailComponent> C_PaySlipFieldDetailComponent { get; set; }
        public virtual DbSet<C_PPH21> C_PPH21 { get; set; }
        public virtual DbSet<C_ReplacementDO> C_ReplacementDO { get; set; }
        public virtual DbSet<C_ReplacementDODetail> C_ReplacementDODetail { get; set; }
        public virtual DbSet<C_Report> C_Report { get; set; }
        public virtual DbSet<C_ResignationType> C_ResignationType { get; set; }
        public virtual DbSet<C_ROGroupTag> C_ROGroupTag { get; set; }
        public virtual DbSet<C_Roster> C_Roster { get; set; }
        public virtual DbSet<C_RosterOverTimeDetail> C_RosterOverTimeDetail { get; set; }
        public virtual DbSet<C_RosterRODetail> C_RosterRODetail { get; set; }
        public virtual DbSet<C_RoundingOvertime> C_RoundingOvertime { get; set; }
        public virtual DbSet<C_RoundingReplacementDO> C_RoundingReplacementDO { get; set; }
        public virtual DbSet<C_SalaryComponent> C_SalaryComponent { get; set; }
        public virtual DbSet<C_SalaryComponentAttendanceCode> C_SalaryComponentAttendanceCode { get; set; }
        public virtual DbSet<C_SalaryComponentDetail> C_SalaryComponentDetail { get; set; }
        public virtual DbSet<C_SalaryComponentEmployee> C_SalaryComponentEmployee { get; set; }
        public virtual DbSet<C_SalaryComponentLengthOfService> C_SalaryComponentLengthOfService { get; set; }
        public virtual DbSet<C_SalaryComponentTag> C_SalaryComponentTag { get; set; }
        public virtual DbSet<C_SettingMandatoryField> C_SettingMandatoryField { get; set; }
        public virtual DbSet<C_Severance> C_Severance { get; set; }
        public virtual DbSet<C_SeveranceMeritPay> C_SeveranceMeritPay { get; set; }
        public virtual DbSet<C_SPTMasa> C_SPTMasa { get; set; }
        public virtual DbSet<C_SPTMasaDetail> C_SPTMasaDetail { get; set; }
        public virtual DbSet<C_SystemInfo> C_SystemInfo { get; set; }
        public virtual DbSet<C_SystemPolling> C_SystemPolling { get; set; }
        public virtual DbSet<C_Tag> C_Tag { get; set; }
        public virtual DbSet<C_Tax> C_Tax { get; set; }
        public virtual DbSet<C_User> C_User { get; set; }
        public virtual DbSet<C_UserDetail> C_UserDetail { get; set; }
        public virtual DbSet<C_UserGroup> C_UserGroup { get; set; }
        public virtual DbSet<C_UserProfile> C_UserProfile { get; set; }
        public virtual DbSet<C_UserProfileDetail> C_UserProfileDetail { get; set; }
        public virtual DbSet<C_UserProfileFind> C_UserProfileFind { get; set; }
        public virtual DbSet<C_Version> C_Version { get; set; }
        public virtual DbSet<C_WorkGroup> C_WorkGroup { get; set; }
        public virtual DbSet<C_WorkingPattern> C_WorkingPattern { get; set; }
        public virtual DbSet<C_WorkingPatternDetail> C_WorkingPatternDetail { get; set; }
        public virtual DbSet<C_WorkingShift> C_WorkingShift { get; set; }
        public virtual DbSet<AppraisalRequest> AppraisalRequests { get; set; }
        public virtual DbSet<AppraisalRequestComment> AppraisalRequestComments { get; set; }
        public virtual DbSet<AppraisalRequestCompetencyCore> AppraisalRequestCompetencyCores { get; set; }
        public virtual DbSet<AppraisalRequestKPI> AppraisalRequestKPIs { get; set; }
        public virtual DbSet<Award> Awards { get; set; }
        public virtual DbSet<ClaimAdjustment> ClaimAdjustments { get; set; }
        public virtual DbSet<ClaimExtension> ClaimExtensions { get; set; }
        public virtual DbSet<ClaimExtensionDetail> ClaimExtensionDetails { get; set; }
        public virtual DbSet<ClaimRequest> ClaimRequests { get; set; }
        public virtual DbSet<ClaimRequestDetail> ClaimRequestDetails { get; set; }
        public virtual DbSet<EmployeeTransaction> EmployeeTransactions { get; set; }
        public virtual DbSet<EmployeeTransfer> EmployeeTransfers { get; set; }
        public virtual DbSet<EmployeeTransferDetail> EmployeeTransferDetails { get; set; }
        public virtual DbSet<LeaveAdjustment> LeaveAdjustments { get; set; }
        public virtual DbSet<LeaveCompensation> LeaveCompensations { get; set; }
        public virtual DbSet<LeaveCompensationDetail> LeaveCompensationDetails { get; set; }
        public virtual DbSet<LeaveExtension> LeaveExtensions { get; set; }
        public virtual DbSet<LeaveExtensionDetail> LeaveExtensionDetails { get; set; }
        public virtual DbSet<LeaveRequest> LeaveRequests { get; set; }
        public virtual DbSet<LND> LNDs { get; set; }
        public virtual DbSet<LNDActionPlan> LNDActionPlans { get; set; }
        public virtual DbSet<LNDAspectAction> LNDAspectActions { get; set; }
        public virtual DbSet<LNDAspectTopic> LNDAspectTopics { get; set; }
        public virtual DbSet<LNDCoach> LNDCoaches { get; set; }
        public virtual DbSet<LNDLastTopic> LNDLastTopics { get; set; }
        public virtual DbSet<LNDObjective> LNDObjectives { get; set; }
        public virtual DbSet<LNDPlanning> LNDPlannings { get; set; }
        public virtual DbSet<LNDPlanningDetail> LNDPlanningDetails { get; set; }
        public virtual DbSet<LNDPreparation> LNDPreparations { get; set; }
        public virtual DbSet<LNDReview> LNDReviews { get; set; }
        public virtual DbSet<Loan> Loans { get; set; }
        public virtual DbSet<LoanDetail> LoanDetails { get; set; }
        public virtual DbSet<NotaDina> NotaDinas { get; set; }
        public virtual DbSet<NotaDinasCC> NotaDinasCCs { get; set; }
        public virtual DbSet<NotaDinasDocument> NotaDinasDocuments { get; set; }
        public virtual DbSet<NotaDinasEmployee> NotaDinasEmployees { get; set; }
        public virtual DbSet<NotaDinasEmployeeDate> NotaDinasEmployeeDates { get; set; }
        public virtual DbSet<OvertimeRequest> OvertimeRequests { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PensionFund> PensionFunds { get; set; }
        public virtual DbSet<PensionFundDetail> PensionFundDetails { get; set; }
        public virtual DbSet<PermitRequest> PermitRequests { get; set; }
        public virtual DbSet<ProcessQueue> ProcessQueues { get; set; }
        public virtual DbSet<ProcessQueueDetail> ProcessQueueDetails { get; set; }
        public virtual DbSet<Resignation> Resignations { get; set; }
        public virtual DbSet<ResignationBranchAsset> ResignationBranchAssets { get; set; }
        public virtual DbSet<ResignationDetail> ResignationDetails { get; set; }
        public virtual DbSet<RollBackTransaction> RollBackTransactions { get; set; }
        public virtual DbSet<RORequest> RORequests { get; set; }
        public virtual DbSet<SalaryAdjustment> SalaryAdjustments { get; set; }
        public virtual DbSet<SalaryAdjustmentDetail> SalaryAdjustmentDetails { get; set; }
        public virtual DbSet<SalaryAdjustmentGlobal> SalaryAdjustmentGlobals { get; set; }
        public virtual DbSet<SalaryAdjustmentGlobalDetail> SalaryAdjustmentGlobalDetails { get; set; }
        public virtual DbSet<SalaryEmployee> SalaryEmployees { get; set; }
        public virtual DbSet<SalaryEmployeeCustom> SalaryEmployeeCustoms { get; set; }
        public virtual DbSet<SalaryEmployeePayment> SalaryEmployeePayments { get; set; }
        public virtual DbSet<SalaryReductionUnReduction> SalaryReductionUnReductions { get; set; }
        public virtual DbSet<StatusAlteration> StatusAlterations { get; set; }
        public virtual DbSet<TaxStatusAlteration> TaxStatusAlterations { get; set; }
        public virtual DbSet<TaxStatusAlterationDetail> TaxStatusAlterationDetails { get; set; }
        public virtual DbSet<Training> Trainings { get; set; }
        public virtual DbSet<TrainingAnswer> TrainingAnswers { get; set; }
        public virtual DbSet<TrainingDetail> TrainingDetails { get; set; }
        public virtual DbSet<TrainingQuestion> TrainingQuestions { get; set; }
        public virtual DbSet<UserActivity> UserActivities { get; set; }
        public virtual DbSet<Warning> Warnings { get; set; }
        public virtual DbSet<C_AutoNumber> C_AutoNumber { get; set; }
        public virtual DbSet<C_AutoNumberDetail> C_AutoNumberDetail { get; set; }
        public virtual DbSet<C_AutoNumberPool> C_AutoNumberPool { get; set; }
        public virtual DbSet<C_AutoNumberPoolDetail> C_AutoNumberPoolDetail { get; set; }
        public virtual DbSet<C_Company> C_Company { get; set; }
        public virtual DbSet<C_Provider> C_Provider { get; set; }
        public virtual DbSet<C_ReportTemplate> C_ReportTemplate { get; set; }
        public virtual DbSet<C_ResignationMatrix> C_ResignationMatrix { get; set; }
        public virtual DbSet<C_SystemStatus> C_SystemStatus { get; set; }
        public virtual DbSet<C_UserProfileCustomFind> C_UserProfileCustomFind { get; set; }
        public virtual DbSet<AttendanceMachine> AttendanceMachines { get; set; }
        public virtual DbSet<MaintenanceLog> MaintenanceLogs { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<ResourcesCenter> ResourcesCenters { get; set; }
    }
}
