//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppraisalRequestKPI
    {
        public System.Guid Id { get; set; }
        public System.Guid AppraisalRequestId { get; set; }
        public string KeyResultArea { get; set; }
        public string KPI { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> Scale { get; set; }
        public Nullable<decimal> Score { get; set; }
        public string TrackingSource { get; set; }
        public string MidYear { get; set; }
        public string Result { get; set; }
        public Nullable<int> LineNumber { get; set; }
    
        public virtual AppraisalRequest AppraisalRequest { get; set; }
    }
}
