//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppraisalRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppraisalRequest()
        {
            this.AppraisalRequestComments = new HashSet<AppraisalRequestComment>();
            this.AppraisalRequestCompetencyCores = new HashSet<AppraisalRequestCompetencyCore>();
            this.AppraisalRequestKPIs = new HashSet<AppraisalRequestKPI>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ReferenceId { get; set; }
        public Nullable<int> SourceType { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Version { get; set; }
        public string Number { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public Nullable<System.Guid> JobId { get; set; }
        public Nullable<System.Guid> BranchId { get; set; }
        public Nullable<System.Guid> OrganizationId { get; set; }
        public Nullable<System.Guid> ClassId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public decimal AutoNumber { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> EndEffectiveDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> TotalKPI { get; set; }
        public Nullable<decimal> PercentageKPI { get; set; }
        public Nullable<decimal> TotalCompetency { get; set; }
        public Nullable<decimal> PercentageCompetency { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> ScoreKPI { get; set; }
        public Nullable<decimal> ScoreCompetency { get; set; }
        public Nullable<System.Guid> CompetencyFinalResultId { get; set; }
        public string PerformanceImprovement { get; set; }
        public string TrainingDevelopment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppraisalRequestComment> AppraisalRequestComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppraisalRequestCompetencyCore> AppraisalRequestCompetencyCores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppraisalRequestKPI> AppraisalRequestKPIs { get; set; }
    }
}
