//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceMachine
    {
        public System.Guid Id { get; set; }
        public string Barcode { get; set; }
        public System.DateTime Date { get; set; }
        public string DutyOnTime { get; set; }
        public string DutyOffTime { get; set; }
        public string Location { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
