//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C__EmployeeSalaryComponent
    {
        public System.Guid Id { get; set; }
        public System.Guid EmployeeId { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string Number { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.Guid> SalaryComponentId { get; set; }
        public Nullable<bool> Calculate { get; set; }
        public string EAmount { get; set; }
        public Nullable<int> EStatus { get; set; }
    }
}
