//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C__Roster
    {
        public System.Guid RosterId { get; set; }
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> CalendarId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.Guid> TagId { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> AttendanceCodeId { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public Nullable<System.Guid> PermitLeaveCodeId { get; set; }
        public Nullable<System.DateTime> PermitLeaveOnDate { get; set; }
        public string PermitLeaveOnTime { get; set; }
        public Nullable<System.DateTime> PermitLeaveOffDate { get; set; }
        public string PermitLeaveOffTime { get; set; }
        public Nullable<System.DateTime> SPLOnDate { get; set; }
        public string SPLOnTime { get; set; }
        public Nullable<System.DateTime> SPLOffDate { get; set; }
        public string SPLOffTime { get; set; }
        public Nullable<decimal> SPLOnHour { get; set; }
        public Nullable<decimal> SPLOffHour { get; set; }
        public Nullable<decimal> SPLOffBreakHour { get; set; }
        public Nullable<decimal> SPLOnBreakHour { get; set; }
        public Nullable<bool> fSPL { get; set; }
        public Nullable<System.Guid> SPLOffBreakId { get; set; }
        public Nullable<System.Guid> SPLOnBreakId { get; set; }
        public Nullable<System.Guid> WorkingShiftId { get; set; }
        public Nullable<System.Guid> ActualAttendanceCodeId { get; set; }
        public Nullable<System.DateTime> DutyOnDate { get; set; }
        public Nullable<System.DateTime> DutyOffDate { get; set; }
        public string DutyOnTime { get; set; }
        public string DutyOffTime { get; set; }
        public Nullable<System.DateTime> BreakOutDate { get; set; }
        public string BreakOutTime { get; set; }
        public Nullable<System.DateTime> BreakInDate { get; set; }
        public string BreakInTime { get; set; }
        public Nullable<System.DateTime> WorkHourInDate { get; set; }
        public string WorkHourInTime { get; set; }
        public Nullable<System.DateTime> WorkHourOutDate { get; set; }
        public string WorkHourOutTime { get; set; }
        public Nullable<System.DateTime> ActualDutyOnDate { get; set; }
        public string ActualDutyOnTime { get; set; }
        public Nullable<System.DateTime> ActualDutyOffDate { get; set; }
        public string ActualDutyOffTime { get; set; }
        public Nullable<System.DateTime> ActualBreakOutDate { get; set; }
        public Nullable<System.DateTime> ActualBreakInDate { get; set; }
        public string ActualBreakOutTime { get; set; }
        public string ActualBreakInTime { get; set; }
        public Nullable<decimal> LateIn { get; set; }
        public Nullable<decimal> EarlyOut { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DayOff { get; set; }
        public Nullable<decimal> WorkingHour { get; set; }
        public Nullable<decimal> SPLDeductionBreak { get; set; }
        public Nullable<int> PermitLeaveType { get; set; }
        public Nullable<System.Guid> PaymentId { get; set; }
        public Nullable<System.Guid> LeaveCodeId { get; set; }
        public Nullable<bool> Invalid { get; set; }
        public Nullable<decimal> ActualWorkingHour { get; set; }
        public string ActualDescription { get; set; }
    }
}
