//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C__SalaryComponent
    {
        public System.Guid Id { get; set; }
        public System.Guid SalaryComponentId { get; set; }
        public string EmployeeFormula { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<int> TaxType { get; set; }
        public Nullable<System.Guid> ReferenceId { get; set; }
    }
}
