//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BaseRate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_BaseRate()
        {
            this.C_BaseRateDetail = new HashSet<C_BaseRateDetail>();
        }
    
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public string Description { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> BasicSalaryType { get; set; }
        public Nullable<int> RunType { get; set; }
        public Nullable<int> DevidedBy { get; set; }
        public Nullable<decimal> DevidedByAmount { get; set; }
        public Nullable<decimal> MultipleAmount { get; set; }
        public Nullable<System.Guid> GroupDataId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public decimal AutoNumber { get; set; }
        public Nullable<decimal> DividerAmount { get; set; }
        public string FormulaAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BaseRateDetail> C_BaseRateDetail { get; set; }
    }
}
