//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BreakDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid BreakId { get; set; }
        public string BreakIn { get; set; }
        public string BreakOut { get; set; }
        public Nullable<decimal> TotalHour { get; set; }
        public Nullable<int> LineNumber { get; set; }
    
        public virtual C_Break C_Break { get; set; }
    }
}
