//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Branch
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<int> Level { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string NPWP { get; set; }
        public string CoreBusiness { get; set; }
        public string Director { get; set; }
        public string NPWPTaxPerson { get; set; }
        public string TaxPerson { get; set; }
        public string KluCode { get; set; }
        public string KPJNo { get; set; }
        public Nullable<bool> UseParentNPWP { get; set; }
        public Nullable<System.Guid> MinimumWageRegionalId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Initial { get; set; }
        public Nullable<System.Guid> RealParentId { get; set; }
        public string ExtraData { get; set; }
        public Nullable<System.Guid> ParentNPWPId { get; set; }
        public string Email { get; set; }
        public Nullable<int> TaxPersonType { get; set; }
        public byte[] SignatureDrawing { get; set; }
        public Nullable<int> fSignature { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
        public string TaxPersonPosition { get; set; }
        public string EFin { get; set; }
        public Nullable<System.Guid> GroupBranch { get; set; }
    }
}
