//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CalendarDetail
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> CalendarId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> DutyOnDate { get; set; }
        public Nullable<System.DateTime> DutyOffDate { get; set; }
        public string DutyOnTime { get; set; }
        public string DutyOffTime { get; set; }
        public Nullable<System.DateTime> BreakInDate { get; set; }
        public string BreakInTime { get; set; }
        public Nullable<System.DateTime> BreakOutDate { get; set; }
        public string BreakOutTime { get; set; }
        public Nullable<System.Guid> TagId { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> WorkingShiftId { get; set; }
        public Nullable<System.Guid> AttendanceCodeId { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<int> DayOff { get; set; }
    
        public virtual C_Calendar C_Calendar { get; set; }
        public virtual C_Tag C_Tag { get; set; }
    }
}
