//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ClaimDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid ClaimId { get; set; }
        public string Name { get; set; }
        public Nullable<int> MinNextClaim { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public string FormulaBenefit { get; set; }
        public Nullable<bool> PaymentEditable { get; set; }
    
        public virtual C_Claim C_Claim { get; set; }
    }
}
