//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Competency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Competency()
        {
            this.C_CompetencyAppraisal = new HashSet<C_CompetencyAppraisal>();
            this.C_CompetencyBranch = new HashSet<C_CompetencyBranch>();
            this.C_CompetencyCore = new HashSet<C_CompetencyCore>();
            this.C_CompetencyFinalResult = new HashSet<C_CompetencyFinalResult>();
            this.C_CompetencyGrade = new HashSet<C_CompetencyGrade>();
            this.C_CompetencyJobResult = new HashSet<C_CompetencyJobResult>();
            this.C_CompetencyKPI = new HashSet<C_CompetencyKPI>();
            this.C_CompetencyKPIResult = new HashSet<C_CompetencyKPIResult>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> MinScale { get; set; }
        public Nullable<int> MaxScale { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public decimal AutoNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_CompetencyAppraisal> C_CompetencyAppraisal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_CompetencyBranch> C_CompetencyBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_CompetencyCore> C_CompetencyCore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_CompetencyFinalResult> C_CompetencyFinalResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_CompetencyGrade> C_CompetencyGrade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_CompetencyJobResult> C_CompetencyJobResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_CompetencyKPI> C_CompetencyKPI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_CompetencyKPIResult> C_CompetencyKPIResult { get; set; }
    }
}
