//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CostNotaDinasMatrixDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid CostNotaDinasMatrixId { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<bool> Meal { get; set; }
        public Nullable<bool> Day { get; set; }
        public Nullable<bool> Transport { get; set; }
        public Nullable<bool> AirPortTax { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<bool> CheckExistingCost { get; set; }
    }
}
