//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CostNotaDinasDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid CostNotaDinasId { get; set; }
        public string Name { get; set; }
        public Nullable<int> TypeLocation { get; set; }
        public Nullable<int> TypeClass { get; set; }
        public Nullable<decimal> AirPortTaxAmount { get; set; }
        public Nullable<System.Guid> CurrencyId { get; set; }
        public Nullable<decimal> MealDayOffAmount { get; set; }
        public Nullable<decimal> TransportAmount { get; set; }
        public Nullable<decimal> DayAmount { get; set; }
        public Nullable<decimal> MealWorkingDayAmount { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public string Description { get; set; }
        public Nullable<bool> OverNight { get; set; }
        public Nullable<int> TypeDestination { get; set; }
    }
}
