//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CompetencyAppraisal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_CompetencyAppraisal()
        {
            this.C_CompetencyCoreAppraisal = new HashSet<C_CompetencyCoreAppraisal>();
            this.C_CompetencyJob = new HashSet<C_CompetencyJob>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid CompetencyId { get; set; }
        public Nullable<decimal> KPI { get; set; }
        public Nullable<decimal> CompetencyCore { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public string Name { get; set; }
    
        public virtual C_Competency C_Competency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_CompetencyCoreAppraisal> C_CompetencyCoreAppraisal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_CompetencyJob> C_CompetencyJob { get; set; }
    }
}
