//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CompetencyCore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_CompetencyCore()
        {
            this.C_CompetencyCoreKeyAction = new HashSet<C_CompetencyCoreKeyAction>();
            this.C_CompetencyCoreAppraisal = new HashSet<C_CompetencyCoreAppraisal>();
            this.C_CompetencyCoreGrade = new HashSet<C_CompetencyCoreGrade>();
            this.C_CompetencyCoreScale = new HashSet<C_CompetencyCoreScale>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid CompetencyId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<int> Level { get; set; }
    
        public virtual C_Competency C_Competency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_CompetencyCoreKeyAction> C_CompetencyCoreKeyAction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_CompetencyCoreAppraisal> C_CompetencyCoreAppraisal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_CompetencyCoreGrade> C_CompetencyCoreGrade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_CompetencyCoreScale> C_CompetencyCoreScale { get; set; }
    }
}
