//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CostNotaDinasDetailTypeTransport
    {
        public System.Guid Id { get; set; }
        public System.Guid CostNotaDinasDetailId { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<decimal> TransportAmount { get; set; }
        public Nullable<decimal> AirPortTaxAmount { get; set; }
        public Nullable<int> LineNumber { get; set; }
    }
}
