//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CustomFieldDefinition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_CustomFieldDefinition()
        {
            this.C_CustomField = new HashSet<C_CustomField>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> DropDownItemId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> DataType { get; set; }
        public Nullable<int> SourceType { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<System.Guid> ReferenceId { get; set; }
        public Nullable<bool> ReportFilter { get; set; }
        public Nullable<int> VisibleReminder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_CustomField> C_CustomField { get; set; }
    }
}
