//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_EmployeeEmergeClaim
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Planning { get; set; }
        public Nullable<decimal> Claimed { get; set; }
        public int Type { get; set; }
        public Nullable<System.Guid> ClaimId { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public Nullable<System.DateTime> OriginalExpiredDate { get; set; }
        public Nullable<bool> Extended { get; set; }
        public System.Guid ParentId { get; set; }
        public Nullable<bool> Expired { get; set; }
        public Nullable<System.Guid> ReferenceId { get; set; }
        public Nullable<System.Guid> ClaimDetailId { get; set; }
        public Nullable<bool> Calculate { get; set; }
        public string ETotal { get; set; }
        public string EPlanning { get; set; }
        public string EClaimed { get; set; }
        public Nullable<int> EStatus { get; set; }
    }
}
