//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_EmployeeTraining
    {
        public System.Guid Id { get; set; }
        public System.Guid EmployeeId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Organizer { get; set; }
        public string Description { get; set; }
        public Nullable<int> Certificate { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<decimal> TrainingFee { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<System.Guid> ProviderId { get; set; }
        public Nullable<System.Guid> TrainingGroupId { get; set; }
    
        public virtual C_Employee C_Employee { get; set; }
    }
}
