//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Employee()
        {
            this.C__Employee = new HashSet<C__Employee>();
            this.C_EmployeeCostCenter = new HashSet<C_EmployeeCostCenter>();
            this.C_EmployeeDependent = new HashSet<C_EmployeeDependent>();
            this.C_EmployeeEducation = new HashSet<C_EmployeeEducation>();
            this.C_EmployeeExpertise = new HashSet<C_EmployeeExpertise>();
            this.C_EmployeeLanguage = new HashSet<C_EmployeeLanguage>();
            this.C_EmployeeOrganization = new HashSet<C_EmployeeOrganization>();
            this.C_EmployeeReference = new HashSet<C_EmployeeReference>();
            this.C_EmployeeRelative = new HashSet<C_EmployeeRelative>();
            this.C_EmployeeTraining = new HashSet<C_EmployeeTraining>();
            this.LeaveRequests = new HashSet<LeaveRequest>();
            this.Resignations = new HashSet<Resignation>();
            this.SalaryEmployees = new HashSet<SalaryEmployee>();
        }
    
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public string Barcode { get; set; }
        public string FullName { get; set; }
        public byte[] UnitDrawing { get; set; }
        public string Address { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Phone { get; set; }
        public string HandPhone { get; set; }
        public string Email { get; set; }
        public Nullable<int> Religion { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Hobby { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<int> EmployeeStatus { get; set; }
        public Nullable<int> OverTimeStatus { get; set; }
        public Nullable<System.Guid> OverTimeGroupId { get; set; }
        public Nullable<System.Guid> BaseRateGroupId { get; set; }
        public string PointOfHire { get; set; }
        public string NPWP { get; set; }
        public Nullable<System.DateTime> NPWPDate { get; set; }
        public Nullable<bool> fNPWP { get; set; }
        public decimal AutoNumber { get; set; }
        public string Contact1 { get; set; }
        public string Contact2 { get; set; }
        public string Contact { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> BranchId { get; set; }
        public Nullable<System.Guid> JobId { get; set; }
        public Nullable<System.Guid> OrganizationId { get; set; }
        public Nullable<System.Guid> ClassId { get; set; }
        public Nullable<int> BloodType { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string Nationality { get; set; }
        public string Ethnic { get; set; }
        public string IdNumber { get; set; }
        public Nullable<System.DateTime> IdNumberExpire { get; set; }
        public string DrivingLicenseA { get; set; }
        public Nullable<System.DateTime> DrivingLicenseAExpire { get; set; }
        public string DrivingLicenseB { get; set; }
        public Nullable<System.DateTime> DrivingLicenseBExpire { get; set; }
        public string DrivingLicenseC { get; set; }
        public Nullable<System.DateTime> DrivingLicenseCExpire { get; set; }
        public string DrivingLicenseB1 { get; set; }
        public Nullable<System.DateTime> DrivingLicenseB1Expire { get; set; }
        public string DrivingLicenseB2 { get; set; }
        public Nullable<System.DateTime> DrivingLicenseB2Expire { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ResignDate { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<System.DateTime> EndEffectiveDate { get; set; }
        public Nullable<int> BasicSalaryType { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<System.Guid> BasicSalaryComponentId { get; set; }
        public Nullable<int> TaxStatus { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> fJPK { get; set; }
        public Nullable<System.DateTime> JPKDate { get; set; }
        public Nullable<bool> fPensionFund { get; set; }
        public string PensionFundNo { get; set; }
        public Nullable<System.DateTime> PensionFundDate { get; set; }
        public string PensionNo { get; set; }
        public Nullable<bool> fPension { get; set; }
        public Nullable<int> JKK { get; set; }
        public string JamSosTekNo { get; set; }
        public Nullable<System.DateTime> JamSosTekDate { get; set; }
        public Nullable<bool> fJamSosTek { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ClaimTaxType { get; set; }
        public Nullable<int> LeaveCompensationTaxType { get; set; }
        public Nullable<int> SourceType { get; set; }
        public Nullable<bool> FlexibleTime { get; set; }
        public Nullable<int> JamSosTekTaxType { get; set; }
        public string UserId { get; set; }
        public Nullable<int> EmployeeTaxStatus { get; set; }
        public string EBasicSalary { get; set; }
        public Nullable<int> EStatus { get; set; }
        public string Password { get; set; }
        public byte[] SignatureDrawing { get; set; }
        public Nullable<bool> ResetPassword { get; set; }
        public Nullable<decimal> BegRSalaryNetto { get; set; }
        public Nullable<decimal> BegRPPH21 { get; set; }
        public string PhoneExtension { get; set; }
        public Nullable<System.Guid> RehireEmployeeId { get; set; }
        public Nullable<System.DateTime> PensionDate { get; set; }
        public Nullable<System.Guid> NPPJamsostekId { get; set; }
        public Nullable<int> fJHT { get; set; }
        public Nullable<System.DateTime> PayrollLastRunDate { get; set; }
        public Nullable<System.DateTime> AttendanceLastRunDate { get; set; }
        public Nullable<System.DateTime> HumanResourcesLastRunDate { get; set; }
        public Nullable<bool> fBPJS { get; set; }
        public Nullable<System.DateTime> BPJSDate { get; set; }
        public string BPJSNo { get; set; }
        public Nullable<System.DateTime> PaymentStartDate { get; set; }
        public Nullable<int> BPJSFamily { get; set; }
        public Nullable<bool> fForeign { get; set; }
        public Nullable<int> TaxCountryCode { get; set; }
        public string KITAS { get; set; }
        public Nullable<System.DateTime> KITASExpire { get; set; }
        public string Passport { get; set; }
        public Nullable<System.DateTime> PassportExpire { get; set; }
        public Nullable<bool> fJP { get; set; }
        public Nullable<System.DateTime> JPDate { get; set; }
        public string FamilyCardNumber { get; set; }
        public Nullable<System.DateTime> FamilyCardNumberExpire { get; set; }
        public Nullable<System.DateTime> FirstEmploymentDate { get; set; }
        public Nullable<int> HireType { get; set; }
        public string City { get; set; }
        public string City1 { get; set; }
        public string City2 { get; set; }
        public string ZipCode { get; set; }
        public string ZipCode1 { get; set; }
        public string ZipCode2 { get; set; }
        public string EmailPayslip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C__Employee> C__Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_EmployeeCostCenter> C_EmployeeCostCenter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_EmployeeDependent> C_EmployeeDependent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_EmployeeEducation> C_EmployeeEducation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_EmployeeExpertise> C_EmployeeExpertise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_EmployeeLanguage> C_EmployeeLanguage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_EmployeeOrganization> C_EmployeeOrganization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_EmployeeReference> C_EmployeeReference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_EmployeeRelative> C_EmployeeRelative { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_EmployeeTraining> C_EmployeeTraining { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveRequest> LeaveRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resignation> Resignations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalaryEmployee> SalaryEmployees { get; set; }
    }
}
