//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_JamSosTek
    {
        public System.Guid Id { get; set; }
        public Nullable<decimal> JKK1 { get; set; }
        public Nullable<decimal> JKK2 { get; set; }
        public Nullable<decimal> JKK3 { get; set; }
        public Nullable<decimal> JKK4 { get; set; }
        public Nullable<decimal> JKK5 { get; set; }
        public Nullable<decimal> JHTComp { get; set; }
        public Nullable<decimal> JHTEmp { get; set; }
        public Nullable<decimal> JK { get; set; }
        public Nullable<decimal> JPK1 { get; set; }
        public Nullable<decimal> JPK2 { get; set; }
        public Nullable<decimal> MaxJPK { get; set; }
        public Nullable<decimal> PensionComp { get; set; }
        public Nullable<decimal> PensionEmp { get; set; }
        public Nullable<decimal> PensionFund { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> Proportional { get; set; }
        public Nullable<decimal> MaxPension { get; set; }
        public Nullable<bool> IncludeBackPay { get; set; }
        public Nullable<decimal> BPJSComp { get; set; }
        public Nullable<decimal> BPJSEmp { get; set; }
        public Nullable<decimal> MaxBPJS { get; set; }
        public Nullable<decimal> BPJSFamily { get; set; }
        public Nullable<bool> UseBPJSFamily { get; set; }
        public Nullable<int> MONTH { get; set; }
        public Nullable<bool> BPJSProportional { get; set; }
        public Nullable<bool> BPJSIncludeBackPay { get; set; }
        public Nullable<decimal> JPEmp { get; set; }
        public Nullable<decimal> JPComp { get; set; }
        public Nullable<decimal> UseOtherPensionOrganizer { get; set; }
        public Nullable<bool> AlwaysUseJHT { get; set; }
        public Nullable<decimal> MaxJP { get; set; }
        public Nullable<int> DefaultJKK { get; set; }
    }
}
