//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_OutputFileDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid OutputFileId { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public string PaddingChar { get; set; }
        public Nullable<int> Align { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> FieldType { get; set; }
        public Nullable<int> Line { get; set; }
    
        public virtual C_OutputFile C_OutputFile { get; set; }
    }
}
