//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_OverTimeGroupTag
    {
        public System.Guid Id { get; set; }
        public System.Guid OverTimeGroupId { get; set; }
        public System.Guid TagId { get; set; }
        public Nullable<int> OverTimeStatusType { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<System.Guid> OverTimeId { get; set; }
        public Nullable<int> OverTimeMinBeforeHour { get; set; }
        public Nullable<int> OverTimeMinAfterHour { get; set; }
        public Nullable<int> OverTimeAfterHour { get; set; }
        public Nullable<int> OverTimeDeductionBreak { get; set; }
        public Nullable<int> OverTimeDeductionWithLateIn { get; set; }
    }
}
