//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PaymentSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_PaymentSchedule()
        {
            this.C_SalaryComponent = new HashSet<C_SalaryComponent>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> OnceDate { get; set; }
        public Nullable<int> RunType { get; set; }
        public Nullable<int> WeeklyDay1 { get; set; }
        public Nullable<int> WeeklyDay2 { get; set; }
        public Nullable<int> MonthlyDay1 { get; set; }
        public Nullable<int> MonthlyDay2 { get; set; }
        public Nullable<int> MonthlyDay21 { get; set; }
        public Nullable<int> MonthlyDay3 { get; set; }
        public Nullable<int> MonthlyDay31 { get; set; }
        public Nullable<int> MonthlyStyle { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public decimal AutoNumber { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CalculationOneFullMonth { get; set; }
        public Nullable<int> WeekCutOffDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SalaryComponent> C_SalaryComponent { get; set; }
    }
}
