//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PaySlipFieldDetailComponent
    {
        public System.Guid Id { get; set; }
        public System.Guid PaySlipFieldDetailId { get; set; }
        public Nullable<System.Guid> SalaryComponentId { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<int> Type { get; set; }
        public string SalaryComponentName { get; set; }
        public string SalaryComponentDescription { get; set; }
        public Nullable<int> PlusMinus { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<int> AlwaysShow { get; set; }
    }
}
