//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Provider
    {
        public System.Guid Id { get; set; }
        public string ProviderName { get; set; }
        public string Category { get; set; }
        public string WebSite { get; set; }
        public string ContactPerson { get; set; }
        public string Phone { get; set; }
        public string HandPhone { get; set; }
        public string Email { get; set; }
    }
}
