//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ReplacementDODetail
    {
        public System.Guid Id { get; set; }
        public System.Guid ReplacementDOId { get; set; }
        public decimal FromHour { get; set; }
        public Nullable<decimal> ToHour { get; set; }
        public Nullable<decimal> Multiply { get; set; }
        public Nullable<int> LineNumber { get; set; }
    
        public virtual C_ReplacementDO C_ReplacementDO { get; set; }
    }
}
