//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ResignationMatrix
    {
        public System.Guid Id { get; set; }
        public Nullable<int> ResignationType { get; set; }
        public Nullable<int> Severance { get; set; }
        public Nullable<int> Merit { get; set; }
        public Nullable<int> Indemnity { get; set; }
        public Nullable<int> Separation { get; set; }
        public Nullable<int> IndemnityBaseRate { get; set; }
    }
}
