//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ROGroupTag
    {
        public System.Guid Id { get; set; }
        public System.Guid ROGroupId { get; set; }
        public System.Guid TagId { get; set; }
        public Nullable<int> ROStatusType { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<System.Guid> ROId { get; set; }
    }
}
