//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_RosterOverTimeDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid RosterId { get; set; }
        public Nullable<System.Guid> OverTimeDetailId { get; set; }
        public Nullable<decimal> Hour { get; set; }
        public Nullable<decimal> Multiply { get; set; }
        public Nullable<decimal> BasicOverTime { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> BackPay { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public string EBasicSalary { get; set; }
        public string EBasicOverTime { get; set; }
        public Nullable<int> EStatus { get; set; }
        public string EAmount { get; set; }
    }
}
