//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SalaryComponent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_SalaryComponent()
        {
            this.C_BaseRateDetail = new HashSet<C_BaseRateDetail>();
            this.C_SalaryComponentAttendanceCode = new HashSet<C_SalaryComponentAttendanceCode>();
            this.C_SalaryComponentDetail = new HashSet<C_SalaryComponentDetail>();
            this.C_SalaryComponentEmployee = new HashSet<C_SalaryComponentEmployee>();
            this.C_SalaryComponentLengthOfService = new HashSet<C_SalaryComponentLengthOfService>();
        }
    
        public System.Guid Id { get; set; }
        public int SourceType { get; set; }
        public System.Guid GroupDataId { get; set; }
        public Nullable<System.Guid> PaymentScheduleId { get; set; }
        public string Number { get; set; }
        public string Description { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> TaxType { get; set; }
        public Nullable<int> GroupBy { get; set; }
        public Nullable<int> EmployeeType { get; set; }
        public string EmployeeFormula { get; set; }
        public Nullable<decimal> EmployeeAmount { get; set; }
        public Nullable<int> RunType { get; set; }
        public Nullable<int> MonthlyDay1 { get; set; }
        public Nullable<int> MonthlyDay2 { get; set; }
        public Nullable<int> MonthlyDay21 { get; set; }
        public Nullable<int> MonthlyDay3 { get; set; }
        public Nullable<int> MonthlyDay31 { get; set; }
        public Nullable<int> MonthlyStyle { get; set; }
        public Nullable<int> AnnuallyDay1 { get; set; }
        public Nullable<int> AnnuallyDay11 { get; set; }
        public Nullable<int> AnnuallyDay2 { get; set; }
        public Nullable<int> AnnuallyDay21 { get; set; }
        public Nullable<int> AnnuallyDay22 { get; set; }
        public Nullable<int> AnnuallyStyle { get; set; }
        public Nullable<System.DateTime> OnceDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<int> EndType { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public decimal AutoNumber { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.Guid> CurrencyId { get; set; }
        public string EEmployeeAmount { get; set; }
        public Nullable<int> EStatus { get; set; }
        public Nullable<int> DailyRunType { get; set; }
        public Nullable<int> StatusEmployee { get; set; }
        public Nullable<int> BStatus { get; set; }
        public Nullable<bool> UsePaymentScheduleRunType { get; set; }
        public Nullable<int> WeeklyDay1 { get; set; }
        public string Note { get; set; }
        public Nullable<int> TransactionType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BaseRateDetail> C_BaseRateDetail { get; set; }
        public virtual C_PaymentSchedule C_PaymentSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SalaryComponentAttendanceCode> C_SalaryComponentAttendanceCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SalaryComponentDetail> C_SalaryComponentDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SalaryComponentEmployee> C_SalaryComponentEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SalaryComponentLengthOfService> C_SalaryComponentLengthOfService { get; set; }
    }
}
