//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Severance
    {
        public System.Guid Id { get; set; }
        public Nullable<decimal> FromAmount { get; set; }
        public Nullable<decimal> ToAmount { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> MONTH { get; set; }
    }
}
