//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SeveranceMeritPay
    {
        public System.Guid Id { get; set; }
        public Nullable<int> SourceType { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<decimal> Resignation { get; set; }
        public Nullable<decimal> Pension { get; set; }
        public Nullable<decimal> PassAway { get; set; }
        public Nullable<decimal> Others { get; set; }
    }
}
