//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SystemInfo
    {
        public System.Guid Id { get; set; }
        public Nullable<int> MinPasswordLength { get; set; }
        public Nullable<int> MaxAccountPasswordAge { get; set; }
        public Nullable<int> MinValidityRetype { get; set; }
        public Nullable<int> MaxLogOnFailed { get; set; }
        public Nullable<System.DateTime> UpdateStamp { get; set; }
        public Nullable<int> LeaveDayType { get; set; }
        public Nullable<int> LeaveDayProportional { get; set; }
        public Nullable<int> DayWorkingHour { get; set; }
        public Nullable<int> WeekWorkingDay { get; set; }
        public Nullable<int> EmergeLeaveDay { get; set; }
        public Nullable<int> ClaimDayType { get; set; }
        public Nullable<int> EmergeClaimDay { get; set; }
        public Nullable<int> ClaimDayProportional { get; set; }
        public Nullable<bool> LeaveAllowMinus { get; set; }
        public Nullable<int> LeaveMaxMinus { get; set; }
        public Nullable<bool> ClaimAllowMinus { get; set; }
        public Nullable<int> DateFormat { get; set; }
        public Nullable<System.DateTime> PayrollLastRunDate { get; set; }
        public Nullable<System.DateTime> PayrollNextRunDate { get; set; }
        public Nullable<System.DateTime> PayrollBackUpLastRunDate { get; set; }
        public Nullable<bool> PayrollRollBack { get; set; }
        public Nullable<bool> PayrollRequirePolling { get; set; }
        public Nullable<int> SetupStatus { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> MaxOverTimeDays { get; set; }
        public Nullable<int> MaxOverTimeWeeks { get; set; }
        public Nullable<bool> UseActiveDirectory { get; set; }
        public Nullable<decimal> MinDenominator { get; set; }
        public Nullable<int> AlertMinus { get; set; }
        public Nullable<int> AlertPlus { get; set; }
        public Nullable<bool> PaymentPeriodMonthly { get; set; }
        public Nullable<int> MaxRangeDate { get; set; }
        public Nullable<int> OverTimeAfterHour { get; set; }
        public Nullable<int> OverTimeDeductionBreak { get; set; }
        public Nullable<System.DateTime> AttendanceLastRunDate { get; set; }
        public Nullable<System.DateTime> AttendanceNextRunDate { get; set; }
        public Nullable<System.DateTime> AttendanceBackUpLastRunDate { get; set; }
        public Nullable<bool> AttendanceRollBack { get; set; }
        public string ActiveDirectoryDomain { get; set; }
        public Nullable<System.DateTime> HRLastRunDate { get; set; }
        public Nullable<System.DateTime> HRNextRunDate { get; set; }
        public Nullable<System.DateTime> HRBackUpLastRunDate { get; set; }
        public Nullable<bool> HRRollBack { get; set; }
        public Nullable<int> MaxOverTimeMonth { get; set; }
        public Nullable<int> PensionFAge { get; set; }
        public Nullable<int> PensionMAge { get; set; }
        public Nullable<bool> OverRideLeave { get; set; }
        public Nullable<bool> ActualDutyComplete { get; set; }
        public string SMTPServer { get; set; }
        public string SMTPUserName { get; set; }
        public string SMTPPassword { get; set; }
        public string SMTPAdminEmail { get; set; }
        public Nullable<bool> KeepMinDenominator { get; set; }
        public Nullable<bool> CollapseData { get; set; }
        public Nullable<bool> SMTPRandomPassword { get; set; }
        public Nullable<bool> HistoryRoster { get; set; }
        public string ESlipSubject { get; set; }
        public string ESlipBody { get; set; }
        public string ESlipResetSubject { get; set; }
        public string ESlipResetBody { get; set; }
        public string ESlipInvitationSubject { get; set; }
        public string ESlipInvitationBody { get; set; }
        public Nullable<int> ClaimDependentAge { get; set; }
        public Nullable<bool> LeaveBecomeOvertime { get; set; }
        public Nullable<bool> AutoNumberTransaction { get; set; }
        public Nullable<bool> EncryptDecrypt { get; set; }
        public Nullable<int> EncryptDecryptStatus { get; set; }
        public Nullable<System.DateTime> PollingLastRunDate { get; set; }
        public Nullable<System.DateTime> PollingNextRunDate { get; set; }
        public Nullable<bool> PollingRollBackStatus { get; set; }
        public Nullable<int> DiffShiftHour { get; set; }
        public Nullable<int> EmployeeTransferPaymentType { get; set; }
        public Nullable<int> ClaimPayment { get; set; }
        public Nullable<int> SMTPPort { get; set; }
        public Nullable<int> allowClaimPayment { get; set; }
        public Nullable<int> SetExportDirectory { get; set; }
        public Nullable<int> Thread { get; set; }
        public Nullable<int> EnableSSL { get; set; }
        public Nullable<int> SeveranceMeritBasedOn { get; set; }
        public Nullable<int> EmployeeHistoryDay { get; set; }
        public Nullable<int> TransactionHistoryDay { get; set; }
        public Nullable<bool> UseBrowseDataCache { get; set; }
        public string BackupLocation { get; set; }
        public Nullable<int> AutoBackup { get; set; }
        public Nullable<bool> UpdateStatisticAfterProcess { get; set; }
        public Nullable<int> DailyPaymentPaidOn { get; set; }
        public string NetworkProxy { get; set; }
        public string NetworkUserName { get; set; }
        public string NetworkPassword { get; set; }
        public Nullable<int> AutoUpdate { get; set; }
        public Nullable<int> SeveranceMeritPaidLeave { get; set; }
        public Nullable<bool> SeveranceMeritLoan { get; set; }
        public Nullable<int> LOSCalculateBy { get; set; }
        public Nullable<bool> UseCostCenter { get; set; }
        public Nullable<System.Guid> LockingGuid { get; set; }
        public Nullable<int> StartNewDayOn { get; set; }
        public Nullable<int> BeforeDutyOn { get; set; }
        public Nullable<int> AfterDutyOn { get; set; }
        public Nullable<int> BeforeDutyOff { get; set; }
        public Nullable<int> AfterDutyOff { get; set; }
        public string DayOffDutyOn { get; set; }
        public string DayOffDutyOff { get; set; }
        public Nullable<bool> SplitPosition { get; set; }
        public Nullable<System.DateTime> SplitPositionDate { get; set; }
        public Nullable<bool> ReplacementDO { get; set; }
        public Nullable<int> ROExpiredBy { get; set; }
        public Nullable<int> ROTotalDays { get; set; }
        public Nullable<int> DayWorkingHourRO { get; set; }
        public Nullable<bool> UseProfile { get; set; }
    }
}
