//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SystemStatus
    {
        public System.Guid Id { get; set; }
        public System.Guid KeyId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> Employee { get; set; }
        public string KEYCode { get; set; }
        public string STCode { get; set; }
        public string DRCode { get; set; }
        public string ENCode { get; set; }
        public string EMCode { get; set; }
    }
}
