//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SystemPolling
    {
        public System.Guid Id { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Method { get; set; }
        public string Password { get; set; }
        public string FileName { get; set; }
        public string TableName { get; set; }
        public string Date { get; set; }
        public string Barcode { get; set; }
        public string Location { get; set; }
        public string DutyOn { get; set; }
        public string DutyOff { get; set; }
        public Nullable<int> DatePosition { get; set; }
        public Nullable<int> DateLength { get; set; }
        public Nullable<int> DateFormat { get; set; }
        public string DateSeparator { get; set; }
        public Nullable<int> DutyOnOffPosition { get; set; }
        public Nullable<int> DutyOnOffLength { get; set; }
        public Nullable<int> DutyOnOffFormat { get; set; }
        public string DutyOnOffSeparator { get; set; }
        public Nullable<int> BarcodePosition { get; set; }
        public Nullable<int> BarcodeLength { get; set; }
        public Nullable<int> LocationPosition { get; set; }
        public Nullable<int> LocationLength { get; set; }
        public Nullable<int> OnOffPosition { get; set; }
        public Nullable<int> OnOffLength { get; set; }
        public string OnOff { get; set; }
        public Nullable<int> RangeDutyOn { get; set; }
        public Nullable<int> RangeDutyOff { get; set; }
        public string SeparatorChar { get; set; }
        public Nullable<System.DateTime> LastRunDate { get; set; }
        public Nullable<System.DateTime> NextRunDate { get; set; }
        public Nullable<bool> RollBackStatus { get; set; }
        public Nullable<int> DelayMinimum { get; set; }
        public Nullable<System.DateTime> UpdateStamp { get; set; }
        public Nullable<int> OccursEvery { get; set; }
        public Nullable<int> FrequencyEveryAmount { get; set; }
        public Nullable<int> FrequencyEvery { get; set; }
        public string FrequencyStartingAt { get; set; }
        public string FrequencyEndingAt { get; set; }
        public Nullable<int> ProcessType { get; set; }
        public Nullable<int> BarcodeOrder { get; set; }
        public Nullable<int> DateOrder { get; set; }
        public Nullable<int> DutyOnOffOrder { get; set; }
        public Nullable<int> LocationOrder { get; set; }
        public Nullable<int> OnOffOrder { get; set; }
        public string OnValue { get; set; }
        public string OffValue { get; set; }
        public Nullable<int> DiffShiftHour { get; set; }
        public string WebServiceMachine { get; set; }
        public string WebServiceUserName { get; set; }
        public string WebServicePassword { get; set; }
        public string Name { get; set; }
        public Nullable<int> IgnoreFirstRow { get; set; }
        public Nullable<int> RangeAfterDutyOn { get; set; }
        public Nullable<int> RangeAfterDutyOff { get; set; }
        public string DayOffDutyOn { get; set; }
        public string DayOffDutyOff { get; set; }
        public string DateOff { get; set; }
        public Nullable<bool> PrioritizeOnOffFlag { get; set; }
        public string Sheet { get; set; }
        public Nullable<bool> FlagAutomatic { get; set; }
    }
}
