//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Tax
    {
        public System.Guid Id { get; set; }
        public Nullable<decimal> PTKPPribadi { get; set; }
        public Nullable<decimal> PTKPIstri { get; set; }
        public Nullable<decimal> PTKPAnak { get; set; }
        public Nullable<decimal> MaxBiayaJabatan { get; set; }
        public Nullable<decimal> BiayaJabatanPercentage { get; set; }
        public Nullable<decimal> PPH21Expatriat { get; set; }
        public Nullable<int> Method { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> FirstCalculate { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> MaxSalaryPem { get; set; }
        public Nullable<decimal> MaxDailyWage { get; set; }
        public Nullable<decimal> MinMonthlyWage { get; set; }
        public Nullable<decimal> MaxMonthlyWage { get; set; }
        public Nullable<decimal> PPH21Wage { get; set; }
        public Nullable<decimal> PPH21TenagaAhli { get; set; }
        public Nullable<int> TaxSeveranceAndMeritPay { get; set; }
        public Nullable<int> MONTH { get; set; }
        public Nullable<int> ClaimTaxType { get; set; }
        public Nullable<int> LeaveTaxType { get; set; }
        public Nullable<bool> UseTaxAllowanceTaxCompany { get; set; }
    }
}
