//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_UserProfile
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PayrollLastRunDate { get; set; }
        public Nullable<System.DateTime> PayrollNextRunDate { get; set; }
        public Nullable<System.DateTime> PayrollBackUpLastRunDate { get; set; }
        public Nullable<bool> PayrollRollBack { get; set; }
        public Nullable<System.DateTime> HRLastRunDate { get; set; }
        public Nullable<System.DateTime> HRNextRunDate { get; set; }
        public Nullable<System.DateTime> HRBackUpLastRunDate { get; set; }
        public Nullable<bool> HRRollBack { get; set; }
        public Nullable<System.DateTime> AttendanceLastRunDate { get; set; }
        public Nullable<System.DateTime> AttendanceNextRunDate { get; set; }
        public Nullable<System.DateTime> AttendanceBackUpLastRunDate { get; set; }
        public Nullable<bool> AttendanceRollBack { get; set; }
        public Nullable<bool> PollingRollBackStatus { get; set; }
        public Nullable<System.DateTime> PollingLastRunDate { get; set; }
        public Nullable<System.DateTime> PollingNextRunDate { get; set; }
    }
}
