//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_UserProfileFind
    {
        public System.Guid Id { get; set; }
        public string ProfileName { get; set; }
        public string Stream { get; set; }
        public string TransactionName { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> DefaultProfile { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Description { get; set; }
    }
}
