//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_User()
        {
            this.C__UserPassword = new HashSet<C__UserPassword>();
        }
    
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ModuleSecurity { get; set; }
        public Nullable<System.Guid> UserGroupId { get; set; }
        public Nullable<bool> ActiveLogin { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string MachineName { get; set; }
        public string IpAddress { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> LastChangePasswordDate { get; set; }
        public Nullable<System.DateTime> UpdateStamp { get; set; }
        public Nullable<bool> Admin { get; set; }
        public Nullable<bool> IsBlocking { get; set; }
        public Nullable<int> BlockingCounter { get; set; }
        public Nullable<System.Guid> BranchId { get; set; }
        public Nullable<System.Guid> JobTitleId { get; set; }
        public Nullable<System.Guid> OrganizationId { get; set; }
        public Nullable<System.DateTime> LastAccessDate { get; set; }
        public Nullable<System.Guid> userProfileId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C__UserPassword> C__UserPassword { get; set; }
    }
}
