//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimExtensionDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid ClaimExtensionId { get; set; }
        public Nullable<System.Guid> EmployeeEmergeClaimId { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public Nullable<System.DateTime> ExtendedDate { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.Guid> ClaimId { get; set; }
        public Nullable<System.Guid> ReferenceId { get; set; }
    
        public virtual ClaimExtension ClaimExtension { get; set; }
    }
}
