//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTransfer
    {
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.Guid> FromJobId { get; set; }
        public Nullable<System.Guid> FromOrganizationId { get; set; }
        public Nullable<System.Guid> FromBranchId { get; set; }
        public Nullable<System.Guid> ToJobId { get; set; }
        public Nullable<System.Guid> ToOrganizationId { get; set; }
        public Nullable<System.Guid> ToBranchId { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public decimal AutoNumber { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> EndEffectiveDate { get; set; }
        public Nullable<System.Guid> EmpTransferReasonId { get; set; }
        public Nullable<System.Guid> FromJobHRId { get; set; }
        public Nullable<System.Guid> FromOrganizationHRId { get; set; }
        public Nullable<System.Guid> FromBranchHRId { get; set; }
        public Nullable<System.Guid> ToJobHRId { get; set; }
        public Nullable<System.Guid> ToOrganizationHRId { get; set; }
        public Nullable<System.Guid> ToBranchHRId { get; set; }
        public Nullable<int> EmployeeTransferType { get; set; }
        public Nullable<System.DateTime> PlacementExpiredDate { get; set; }
        public Nullable<System.Guid> EmployeeTransferParentId { get; set; }
    
        public virtual C_Job C_Job { get; set; }
        public virtual C_Job C_Job1 { get; set; }
        public virtual C_Organization C_Organization { get; set; }
        public virtual C_Organization C_Organization1 { get; set; }
    }
}
