//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveAdjustment
    {
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public Nullable<System.Guid> LeaveCodeId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public Nullable<int> Adjustment { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public decimal AutoNumber { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> UnitType { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.Guid> NewLeaveCodeId { get; set; }
    
        public virtual C_Leave C_Leave { get; set; }
    }
}
