//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LND
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LND()
        {
            this.LNDActionPlans = new HashSet<LNDActionPlan>();
            this.LNDAspectActions = new HashSet<LNDAspectAction>();
            this.LNDAspectTopics = new HashSet<LNDAspectTopic>();
            this.LNDCoaches = new HashSet<LNDCoach>();
            this.LNDLastTopics = new HashSet<LNDLastTopic>();
            this.LNDObjectives = new HashSet<LNDObjective>();
            this.LNDPreparations = new HashSet<LNDPreparation>();
            this.LNDReviews = new HashSet<LNDReview>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> LNDPlanningDetailId { get; set; }
        public Nullable<System.Guid> ReferenceId { get; set; }
        public string Number { get; set; }
        public string Description { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public Nullable<System.Guid> JobId { get; set; }
        public Nullable<System.Guid> OrganizationId { get; set; }
        public Nullable<System.Guid> BranchId { get; set; }
        public Nullable<System.Guid> ClassId { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<int> Type { get; set; }
        public string TypeDescription { get; set; }
        public Nullable<int> TypeLocation { get; set; }
        public Nullable<int> Yos { get; set; }
        public Nullable<int> YosJob { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public decimal AutoNumber { get; set; }
        public Nullable<int> Status { get; set; }
        public string Topic { get; set; }
        public string TopicPlan { get; set; }
        public Nullable<decimal> Expense { get; set; }
        public string ProviderName { get; set; }
        public string ProviderAddress { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> TotalWork { get; set; }
        public string Location { get; set; }
        public string Summary { get; set; }
        public string Reason { get; set; }
        public string WorkGoals { get; set; }
        public string ActualCondition { get; set; }
        public string DevelopmentGoals { get; set; }
        public string Skill { get; set; }
        public Nullable<int> TypeMethod { get; set; }
        public Nullable<int> Month { get; set; }
        public string Notes { get; set; }
        public string Problem { get; set; }
        public Nullable<int> SourceType { get; set; }
        public Nullable<bool> Evaluation { get; set; }
        public string EvaluationAction { get; set; }
        public Nullable<int> EvaluationStatus { get; set; }
        public string EvaluationResult { get; set; }
        public Nullable<System.Guid> CurrencyId { get; set; }
        public string TypeMethodDescription { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<bool> Certificate { get; set; }
        public string TypeMethodNotes { get; set; }
        public Nullable<decimal> LNDTopicCostAmount { get; set; }
        public Nullable<System.Guid> LNDTopicId { get; set; }
        public Nullable<System.Guid> PlanCurrencyId { get; set; }
        public Nullable<int> RealizationMonth { get; set; }
        public Nullable<bool> Pending { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LNDActionPlan> LNDActionPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LNDAspectAction> LNDAspectActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LNDAspectTopic> LNDAspectTopics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LNDCoach> LNDCoaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LNDLastTopic> LNDLastTopics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LNDObjective> LNDObjectives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LNDPreparation> LNDPreparations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LNDReview> LNDReviews { get; set; }
    }
}
