//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceLog
    {
        public System.Guid Id { get; set; }
        public int TaskType { get; set; }
        public int RunType { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public string Description { get; set; }
    }
}
