//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public System.Guid Id { get; set; }
        public byte[] Image { get; set; }
        public string NewsTitle { get; set; }
        public Nullable<System.DateTime> NewsDate { get; set; }
        public Nullable<int> NewsIndex { get; set; }
        public string NewsSynopsis { get; set; }
        public string NewsDetailLink { get; set; }
        public Nullable<int> NewsType { get; set; }
    }
}
