//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaDina
    {
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.Guid> FromEmployeeId { get; set; }
        public Nullable<System.Guid> FromBranchId { get; set; }
        public Nullable<System.Guid> FromOrganizationId { get; set; }
        public Nullable<System.Guid> FromJobId { get; set; }
        public Nullable<System.Guid> FromClassId { get; set; }
        public Nullable<System.Guid> ToEmployeeId { get; set; }
        public Nullable<System.Guid> ToBranchId { get; set; }
        public Nullable<System.Guid> ToOrganizationId { get; set; }
        public Nullable<System.Guid> ToJobId { get; set; }
        public Nullable<System.Guid> ToClassId { get; set; }
        public string BudgetNumber { get; set; }
        public string TaskNumber { get; set; }
        public string Activity { get; set; }
        public string Location { get; set; }
        public string Content { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> TypeDirector { get; set; }
        public Nullable<int> TypeClass { get; set; }
        public Nullable<int> TypeOverNight { get; set; }
        public Nullable<int> TypeLocation { get; set; }
        public string TypeLocationDescription { get; set; }
        public Nullable<int> TypeSchedule { get; set; }
        public Nullable<System.Guid> CostNotaDinasDetailId { get; set; }
        public Nullable<System.Guid> CostNotaDinasActivityDetailId { get; set; }
        public string CostNotaDinasActivityDetailDescription { get; set; }
        public Nullable<int> DepartTypeTransport { get; set; }
        public Nullable<int> ArriveTypeTransport { get; set; }
        public Nullable<decimal> MealAmount { get; set; }
        public Nullable<int> MealFundType { get; set; }
        public string MealFundDescripton { get; set; }
        public Nullable<decimal> DayAmount { get; set; }
        public Nullable<decimal> FDayAmount { get; set; }
        public Nullable<System.Guid> DayCurrencyId { get; set; }
        public Nullable<decimal> DayCurrencyRate { get; set; }
        public Nullable<int> DayFundType { get; set; }
        public string DayFundDescription { get; set; }
        public Nullable<System.Guid> DayPayCurrencyId { get; set; }
        public Nullable<decimal> DayPayAmount { get; set; }
        public Nullable<decimal> FDayPayAmount { get; set; }
        public Nullable<decimal> DayPayCurrencyRate { get; set; }
        public Nullable<decimal> DayRemainingAmount { get; set; }
        public Nullable<decimal> FDayRemainingAmount { get; set; }
        public Nullable<decimal> TransportAmount { get; set; }
        public Nullable<int> TransportFundType { get; set; }
        public string TransportFundDescription { get; set; }
        public Nullable<decimal> AirPortTaxAmount { get; set; }
        public Nullable<int> AirPortTaxFundType { get; set; }
        public string AirPortTaxFundDescription { get; set; }
        public Nullable<decimal> OtherAmount { get; set; }
        public Nullable<decimal> FOtherAmount { get; set; }
        public Nullable<decimal> OtherCurrencyRate { get; set; }
        public Nullable<System.Guid> OtherCurrencyId { get; set; }
        public Nullable<int> OtherFundType { get; set; }
        public string OtherFundDescription { get; set; }
        public Nullable<decimal> TicketAmount { get; set; }
        public Nullable<decimal> FTicketAmount { get; set; }
        public Nullable<decimal> TicketCurrencyRate { get; set; }
        public Nullable<System.Guid> TicketCurrencyId { get; set; }
        public Nullable<int> TicketFundType { get; set; }
        public string TicketFundDescription { get; set; }
        public Nullable<decimal> HotelAmount { get; set; }
        public Nullable<decimal> FHotelAmount { get; set; }
        public Nullable<System.Guid> HotelCurrencyId { get; set; }
        public Nullable<decimal> HotelCurrencyRate { get; set; }
        public Nullable<int> HotelFundType { get; set; }
        public string HotelFundDescription { get; set; }
        public Nullable<decimal> PassportAmount { get; set; }
        public Nullable<int> PassportFundType { get; set; }
        public string PassportFundDescription { get; set; }
        public Nullable<decimal> VisaAmount { get; set; }
        public Nullable<decimal> FVisaAmount { get; set; }
        public Nullable<decimal> VisaCurrencyRate { get; set; }
        public Nullable<System.Guid> VisaCurrencyId { get; set; }
        public Nullable<int> VisaFundType { get; set; }
        public string VisaFundDescription { get; set; }
        public Nullable<decimal> HotelTransitAmount { get; set; }
        public Nullable<decimal> FHotelTransitAmount { get; set; }
        public Nullable<decimal> HotelTransitCurrencyRate { get; set; }
        public Nullable<System.Guid> HotelTransitCurrencyId { get; set; }
        public Nullable<int> HotelTransitFundType { get; set; }
        public string HotelTransitFundDescription { get; set; }
        public Nullable<decimal> InsuranceAmount { get; set; }
        public Nullable<decimal> FInsuranceAmount { get; set; }
        public Nullable<decimal> InsuranceCurrencyRate { get; set; }
        public Nullable<System.Guid> InsuranceCurrencyId { get; set; }
        public Nullable<int> InsuranceFundType { get; set; }
        public string InsuranceFundDescription { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public decimal AutoNumber { get; set; }
        public Nullable<int> Status { get; set; }
        public string ActivityDate { get; set; }
        public Nullable<int> TypeDestination { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
    }
}
