//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public System.Guid Id { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public System.Guid PaymentScheduleId { get; set; }
        public Nullable<int> Status { get; set; }
        public string Period { get; set; }
        public Nullable<System.DateTime> FixFromDate { get; set; }
        public Nullable<System.DateTime> FixToDate { get; set; }
        public string PaymentPeriod { get; set; }
        public Nullable<System.DateTime> PaymentFixFromDate { get; set; }
        public Nullable<System.DateTime> PaymentFixToDate { get; set; }
        public Nullable<System.DateTime> PaymentFromDate { get; set; }
        public Nullable<System.DateTime> PaymentToDate { get; set; }
        public Nullable<int> LineNumber { get; set; }
    }
}
