//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessQueue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProcessQueue()
        {
            this.ProcessQueueDetails = new HashSet<ProcessQueueDetail>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ReferenceId { get; set; }
        public Nullable<int> SourceType { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> NextRunDate { get; set; }
        public decimal AutoNumber { get; set; }
        public Nullable<int> EndType { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Occurrence { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.Guid> ResignationId { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> StatusEmployee { get; set; }
        public Nullable<System.DateTime> OriginalEndDate { get; set; }
        public Nullable<System.Guid> KeyId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessQueueDetail> ProcessQueueDetails { get; set; }
    }
}
