//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryAdjustment
    {
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> OldClassId { get; set; }
        public Nullable<System.Guid> OldGradeId { get; set; }
        public Nullable<int> OldBasicSalaryType { get; set; }
        public Nullable<decimal> OldBasicSalary { get; set; }
        public Nullable<System.Guid> OldSalaryComponentId { get; set; }
        public Nullable<System.Guid> OldSalaryComponentEmployeeId { get; set; }
        public Nullable<System.Guid> NewClassId { get; set; }
        public Nullable<System.Guid> NewGradeId { get; set; }
        public Nullable<int> NewBasicSalaryType { get; set; }
        public Nullable<decimal> NewBasicSalary { get; set; }
        public Nullable<System.Guid> NewSalaryComponentId { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public Nullable<System.DateTime> BackPayDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public decimal AutoNumber { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.Guid> ReferenceId { get; set; }
        public Nullable<System.Guid> BackPayReferenceId { get; set; }
        public string ENewBasicSalary { get; set; }
        public string EOldBasicSalary { get; set; }
        public Nullable<int> EStatus { get; set; }
        public Nullable<bool> OverTimeBackPay { get; set; }
    }
}
