//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryReductionUnReduction
    {
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public Nullable<System.Guid> BranchId { get; set; }
        public Nullable<System.Guid> JobId { get; set; }
        public Nullable<System.Guid> OrganizationId { get; set; }
        public Nullable<System.DateTime> ReductionToDate { get; set; }
        public Nullable<System.DateTime> ReductionFromDate { get; set; }
        public Nullable<decimal> ReductionAmountPercentage { get; set; }
        public string ReductionDescription { get; set; }
        public Nullable<System.DateTime> UnReductionDate { get; set; }
        public string UnReductionDescription { get; set; }
        public string UnReductionBy { get; set; }
        public string ReductionBy { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public decimal AutoNumber { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.Guid> ReferenceId { get; set; }
    }
}
