//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryEmployeeCustom
    {
        public System.Guid EmployeeId { get; set; }
        public System.Guid PaymentId { get; set; }
        public int TaxType { get; set; }
        public System.Guid BranchId { get; set; }
        public Nullable<int> EStatus { get; set; }
        public Nullable<decimal> SMEALALLOWANCE { get; set; }
        public Nullable<decimal> STUNJANGANBPJSKESEHATAN { get; set; }
        public Nullable<decimal> STUNJANGANJABATAN { get; set; }
        public Nullable<decimal> STUNJANGANJHT { get; set; }
        public Nullable<decimal> STUNJANGANJP { get; set; }
        public Nullable<decimal> STUNJANGANLAIN { get; set; }
        public Nullable<decimal> STUNJANGANRUMAH { get; set; }
        public Nullable<decimal> STUNJANGANTRANSPORT { get; set; }
        public Nullable<decimal> SOverTime { get; set; }
        public Nullable<decimal> SLEMBURMIDNIGHTSALES { get; set; }
        public Nullable<decimal> SUNPAIDLEAVE { get; set; }
        public Nullable<decimal> STHR { get; set; }
        public Nullable<decimal> CSTHR { get; set; }
        public int StatusEmployee { get; set; }
        public Nullable<decimal> Sswda { get; set; }
        public Nullable<decimal> Sswdp { get; set; }
        public Nullable<decimal> STUNJANGANLAINGROSS { get; set; }
        public Nullable<decimal> STUNJANGANLAINGROSSUP { get; set; }
        public Nullable<decimal> SDASARBPJS { get; set; }
        public Nullable<decimal> SBPJSMINUS { get; set; }
        public Nullable<decimal> SSeverance { get; set; }
        public Nullable<decimal> CSSeverance { get; set; }
        public Nullable<decimal> STunjanganBPJS { get; set; }
        public Nullable<decimal> SMEALALLOWANCEGROSSUP { get; set; }
        public Nullable<decimal> STHRGROSS { get; set; }
        public Nullable<decimal> CSTHRGROSS { get; set; }
        public Nullable<decimal> STHRGROSSUP { get; set; }
        public Nullable<decimal> CSTHRGROSSUP { get; set; }
    }
}
