//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryAdjustmentGlobalDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid SalaryAdjustmentGlobalId { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public Nullable<System.Guid> SalaryComponentEmployeeId { get; set; }
        public Nullable<decimal> OldAmount { get; set; }
        public Nullable<decimal> NewAmount { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<System.Guid> ReferenceId { get; set; }
        public Nullable<System.Guid> BackPayReferenceId { get; set; }
        public Nullable<bool> Expired { get; set; }
        public string EOldAmount { get; set; }
        public string ENewAmount { get; set; }
        public Nullable<int> EStatus { get; set; }
        public Nullable<System.Guid> OldClassId { get; set; }
        public Nullable<System.Guid> NewClassId { get; set; }
    
        public virtual SalaryAdjustmentGlobal SalaryAdjustmentGlobal { get; set; }
    }
}
