//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPerhitunganPajak.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string SubjectOfTraining { get; set; }
        public string HRDGAManager { get; set; }
        public string TrainingInstitution { get; set; }
        public Nullable<System.DateTime> CourseStartDate { get; set; }
        public Nullable<System.DateTime> CourseEndDate { get; set; }
        public string Venue { get; set; }
        public Nullable<decimal> TrainingFee { get; set; }
        public string DepartmentManager { get; set; }
        public string VPM { get; set; }
        public Nullable<System.DateTime> CashDate { get; set; }
        public string PaymentMethod { get; set; }
        public string FASupervisor { get; set; }
        public string CurrencyName { get; set; }
        public Nullable<int> CurrencyType { get; set; }
        public string AccountHolder { get; set; }
        public string Bank { get; set; }
        public string BankBranch { get; set; }
        public string AccountNo { get; set; }
        public string HRDSuperintendent { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int AutoNumber { get; set; }
        public Nullable<System.Guid> JobId { get; set; }
        public Nullable<System.Guid> OrganizationId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public string Description { get; set; }
        public string MemoTo { get; set; }
        public Nullable<System.Guid> ClassId { get; set; }
    }
}
